Repository hexis-revival/hexagon, pull requests merged in 2024-12, with the labels that each got.

#18 Implement spectating
  hnet/constants.go
  hnet/handler.go
  hnet/objects.go
  hnet/parsers.go
  hnet/player.go
  hnet/server.go
  hnet/writers.go
Labels: feature, packets

#24 Add has map packet for spectator
  common/io.go
  hnet/constants.go
  hnet/handler.go
  hnet/objects.go
  hnet/parsers.go
  hnet/writers.go
Labels: feature, packets

#28 Add beatmap storage interface
  common/storage.go
Labels: feature

#27 Implement `/web/bss-genid.php` endpoint
  common/database_queries.go
  common/database_schemas.go
  hscore/beatmaps.go
Labels: feature

#29 Implement `/web/bss-upload.php` endpoint
  Dockerfile
  common/audio.go
  common/database_queries.go
  common/database_schemas.go
  common/go.mod
  common/go.sum
  common/storage.go
  common/thumbnail.go
  go.mod
  go.sum
  hnet/go.mod
  hnet/go.sum
  hscore/beatmaps.go
  hscore/go.mod
  hscore/go.sum
Labels: feature

#30 Implement `/web/bss-gentid.php` logic
  hscore/beatmaps.go
Labels: feature

#31 Implement `/web/bss-post.php` logic
  hscore/beatmaps.go
Labels: feature

#32 Add beatmap header to leaderboard response
  hnet/handler.go
  hnet/objects.go
  hnet/parsers.go
  hnet/writers.go
Labels: feature, packets

#34 Add forum database schema
  common/database_queries.go
  common/database_schemas.go
Labels: feature, database

#35 Implement forum topics inside beatmap submission
  common/database_queries.go
  common/database_schemas.go
  hscore/beatmaps.go
Labels: enhancement

#36 Migrate `score` table to hexagon
  common/constants.go
  common/database_queries.go
  common/database_schemas.go
  hscore/scoring.go
Labels: feature, database

#37 Add basic structure for score submission & implement database inserts
  common/constants.go
  common/database_queries.go
  common/database_schemas.go
  common/storage.go
  hscore/authentication.go
  hscore/beatmaps.go
  hscore/objects.go
  hscore/parsing.go
  hscore/scoring.go
Labels: feature, api

#39 Implement stats refresh packet
  hnet/constants.go
  hnet/handler.go
  hnet/player.go
Labels: feature, packets

#38 Add user stats updates on score submission
  common/database_queries.go
  hscore/scoring.go
Labels: feature, api

#40 Implement playtime updates
  common/database_queries.go
  hnet/handler.go
  hnet/objects.go
  hnet/parsers.go
Labels: feature

#41 Implement user ranking system
  common/database_schemas.go
  common/rankings.go
  hscore/scoring.go
Labels: feature

#42 Add score validation
  common/database_schemas.go
  common/logging.go
  hscore/objects.go
  hscore/parsing.go
  hscore/scoring.go
Labels: enhancement, api
